# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 00:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_remove_dhs_cluster_name'),
    ]

    operations = [
    ]
