# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20170414_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhs_cluster',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dhs_cluster',
            name='data_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dhs_cluster',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='dhs_cluster',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='wealth_decile',
            field=models.IntegerField(null=True),
        ),
    ]
