# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_auto_20170418_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhs_cluster',
            name='data_year',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
