# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_region_boundary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='boundary',
            new_name='geom',
        ),
    ]
